In [1]:
# Import 3rd party libraries
import pandas as pd
import seaborn as sns
import geopandas as gpd
import matplotlib.pylab as plt
import folium


# Configure Notebook
%matplotlib inline
plt.style.use('fivethirtyeight')
sns.set_context("notebook")
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r'C:\Users\sarah\Downloads\Gulllake.csv')
data.head()

,Location,Temperature (C ),pH,Conductivity (uS/cm),DO mg/L,DO %,Average PO,Date,Time,year,PO (ug/L-1)
0,Gull Bay (6m),18.8,7.26,68.1,7.73,84.1,0.027,05-Aug-19,2:00:00 PM,2019,0.000000
1,Gull Bay (12m),9,6.89,55.1,9.29,81.3,0.027,05-Aug-19,2:00:00 PM,2019,26.666667
2,Gull Bay (15m),7.8,6.91,54.3,11.56,96.2,0.020,05-Aug-19,2:00:00 PM,2019,20.000000
3,Gull River (0m),24.2,7.58,74.4,6.92,87.7,0.020,05-Aug-19,2:00:00 PM,2019,20.000000
4,Gull Bay (1m),24.3,7.35,71.5,5.37,64.3,0.033,05-Aug-19,2:00:00 PM,2019,33.333333

In [3]:
data['Location'].unique()

array(['Gull Bay (6m)', 'Gull Bay (12m)', 'Gull Bay (15m)',
       'Gull River (0m)', 'Gull Bay (1m)', 'Gull Bay (9m)',
       'Gull Bay (20m)', 'Gull Bay (3m)', 'Gull Bay (8m)',
       'Gull Bay (27m)', 'Camp Creek (Outflow)', 'Shoreline', 'Dock (0m)',
       'Camp Creek (mid)', 'Rain Water', 'Gull Bay (5m)',
       'Gull Bay (10m)', 'Camp Creek (Weir)', 'Camp Creek (Bridge)',
       'Gull Bay (25m)', 'Gull Bay (2.5m)', 'Gull River (1m)',
       'Rackety Creek Outflow (0m)', 'Little Bob Lake',
       'Rackety Creek Outflow (2.5m)', 'Rackety Creek Outflow (24m)',
       'Camp Creek (Wetlands)', 'Camp Creek (Wier)', 'Camp Creek (Mid)',
       'Little Bob Lake ', 'GullBay (27m)', 'Gull Lake Outflow (2.5m)',
       'Rackety Creek Upstream', 'Rackety Creek (Upstream)',
       'Rackety Creek  (Midstream)', 'Gull Bay (16m)',
       'Gull River (2.5m)', 'Camp Creek (Weir) ', 'Gull River  (2.5m)',
       'Rackety Creek at Weir ', 'Rackety Creek Midstream ',
       'Gull Bay (45m)', 'Camp Creek (bridge)', 'Rain   ',
       'Rackety Creek Outflow (6m)', 'Camp Creek (wetlands)',
       'Camp creek (outflow)', 'rain   ', 'Gull Lake outflow (2.5m)',
       'Dock (2.5m)', 'Rackety Creek (upstream)', 'Bob Lake',
       'Gull Bay (30m)', 'Gull Bay(5m)', 'Gull River (14m)', 'Rain',
       'Dock (1m)', 'Gull River Output (4.8m)', 'Gull River (5m)',
       'Well #1', 'Gull River (15m)', 'Camp Creek Outflow ',
       'Shoreline (Pumphouse)', 'Gull River (9m)',
       'Rackety Creek Outflow (27m)', 'Well #4', 'Well #2',
       'Rackety Creek Outflow (15m)', 'Rackety Creek Outflow (5m)',
       'Well #3', 'Shoreline (School house)',
       'South western point 10 meters southwest of SWP - NaN',
       'Gull Lake (10m from Camp Creek Outflow)', 'Camp creek (Weir)',
       'Rackety creek Outflow (0m)',
       'South western point 10 meters southwest of SWP',
       'Gull Lake (lily pads)', 'Gull Lake (30m from Camp Creek Outflow)',
       'Dock (5m)', 'Shoreline (Dock)', 'Rackety Creek Outflow (9m)',
       'Gull Bay (40m)', 'Gull River (3m)', 'Gull River (22m)',
       'Rackety Creek (0m)', 'Rackety Creek  (1m)', 'Water', 'Well #1 ',
       'Well #4 ', 'Dock (15m)', 'well #4', 'Rackety Creek Outflow (30m)',
       'Dock (9m)', 'Rackety Creek Outflow (6.1m)',
       'Rackety Creek Outflow (1.4m)', 'Gull River (1.4m)', 'well #2 ',
       'well#3', 'well #3', 'Rackety Creek Outflow (1m)', 'Dock (3m)',
       'Camp creek (weir)', 'Gull Lake (27m from Camp Creek Outflow)',
       'Camp creek (end)', 'Camp creek (bridge)', 'Camp Creek (weir)',
       'well #1', 'Gull Bay (0m)', nan, 'Small dock on Gull Lake',
       'Well #6', 'Gull River (2m)', 'Rain ', 'Camp Creek (Wetland)',
       'Rackety Creek Outflow (2m)', 'Rackety Creek Outflow (10m)',
       "Miner's Bay (2m)", 'Gull Bay (2m)', ' Gull Bay (0m)',
       ' Gull Bay (10m)', 'camp creek (wetlands)', ' Gull Bay (15m)',
       'North Pigeon Lake Inlet, surface at creek', 'Camp creek (mid)',
       ' Gull Bay (2m)', 'Rackety Creek Outflow (8m)', ' Gull Bay (8m)',
       'Gull Lake (15m from Camp Creek Outflow)', 'Gull River (8m)'],
      dtype=object)

In [4]:
ll = '('
ff = ')'
vv = data['Location'].tolist()
kk = []
jj = []
 
# length of substring 1 is added to
# get string from next character

for i in vv:
    if ll in str(i):
        idx1 = i.index(ll)
        idx2 = i.index(ff)
        res = i[idx1 + 1: idx2]
        kk.append(res)
        mm = i[:idx1]
        jj.append(mm)
    else:
        kk.append('')
        jj.append(i)


print(kk)
print(jj)

['6m', '12m', '15m', '0m', '1m', '9m', '20m', '3m', '8m', '27m', 'Outflow', 'Outflow', 'Outflow', 'Outflow', 'Outflow', '', '1m', '6m', '20m', '0m', '0m', '0m', 'mid', 'mid', 'mid', '', '5m', '10m', '12m', 'mid', 'mid', 'mid', 'Weir', 'Weir', 'Bridge', 'Bridge', 'Bridge', 'Weir', 'Outflow', 'Outflow', 'Outflow', '', '', '', '25m', '2.5m', '1m', 'Weir', 'Bridge', '0m', '', '0m', '', 'Weir', 'Bridge', 'Outflow', 'Weir', 'Bridge', '2.5m', '24m', '25m', 'Wetlands', 'Wier', 'Mid', 'Bridge', 'Wier', 'Mid', 'Bridge', '2.5m', '1m', '', '27m', '2.5m', '2.5m', '27m', 'Mid', 'Wier', '', '2.5m', '2.5m', '0m', '', '0m', '0m', 'Upstream', '', '0m', 'Upstream', 'Midstream', '', '2.5m', '16m', 'Outflow', '2.5m', '2.5m', '0m', 'Outflow', '', 'Outflow', '0m', 'Weir', 'Outflow', 'Mid', 'Outflow', '0m', 'Weir', '0m', '', '2.5m', '0m', '', '', '2.5m', '45m', '8m', '2.5m', '', 'Wetlands', '0m', 'bridge', 'Weir', 'mid', '', '2.5m', '6m', 'wetlands', 'outflow', '', '2.5m', '2.5m', '2.5m', 'upstream', '', '', 'Outflow', '6m', 'Weir', '30m', 'Bridge', '8m', 'mid', 'mid', 'Outflow', '20m', '8m', 'Weir', '2.5m', '5m', '14m', '', '1m', '4.8m', '5m', 'Weir', 'Bridge', 'Mid', '8m', 'Outflow', '0m', '', '15m', 'Bridge', '', 'Pumphouse', '9m', 'Weir', '27m', '15m', 'Weir', '', '', '15m', 'Outflow', '5m', 'Outflow', '', 'Wetlands', '0m', '0m', 'School house', '', 'School house', '10m from Camp Creek Outflow', 'Weir', 'Wetlands', '15m', '0m', '0m', 'Bridge', '9m', '', 'Outflow', 'Outflow', 'Bridge', 'Weir', 'Weir', 'Outflow', '', 'Mid', 'Bridge', '0m', 'Bridge', 'Mid', 'Bridge', 'School house', '', 'lily pads', '0m', 'Wetlands', 'Weir', '', 'Weir', '10m from Camp Creek Outflow', '30m from Camp Creek Outflow', '0m', 'Bridge', 'lily pads', '5m', 'Pumphouse', 'Wetlands', 'Bridge', 'Mid', 'Outflow', 'Outflow', 'Outflow', 'Outflow', 'Weir', 'Weir', 'Weir', 'Bridge', 'Mid', 'Wetlands', 'Wetlands', 'Wetlands', 'Bridge', 'Weir', 'Mid', 'Outflow', 'Outflow', 'Outflow', '', '9m', '0m', 'Dock', 'Dock', '12m', '5m', '15m', '9m', '15m', '1m', '40m', '3m', '22m', '', '1m', '0m', 'School house', '0m', '1m', '', 'Weir', '', '', '', '', '', '', '15m', 'Outflow', 'lily pads', '', 'Bridge', 'Mid', 'Mid', '15m', '', 'Bridge', 'Wetlands', 'Outflow', '15m', 'Outflow', 'lily pads', '', 'Wetlands', 'Mid', 'Bridge', 'Pumphouse', 'Outflow', '9m', 'Wetlands', '', '', '', 'Weir', 'Weir', '0m', '', '30m', '5m', 'Pumphouse', '0m', '', '', '', 'Weir', '9m', '0m', 'Outflow', 'Outflow', '9m', 'Weir', 'Bridge', '', 'Mid', '', '6.1m', '1.4m', '1.4m', '6.1m', '1.4m', '', '', '9m', '0m', 'Weir', 'Bridge', '', '', '15m', '0m', 'Outflow', 'Pumphouse', 'Weir', '', '1m', 'Wetlands', '15m', '3m', '0m', 'weir', 'outflow', '', '9m', 'outflow', '', '', '27m from Camp Creek Outflow', 'end', 'bridge', '1m', '', 'weir', '', 'Wetlands', '', '', 'Mid', '9m', '40m', 'outflow', '', '9m', '0m', 'Weir', '', 'mid', '15m', '9m', '', '15m', 'Wetlands', '', '', '', '', 'outflow', 'outflow', '', 'Weir', '30m', '0m', '', '0m', '', '0m', '15m', '5m', 'bridge', '', '', '', 'Weir', '3m', '10m', '', '5m', '15m', '', '8m', '0m', 'Weir', '2m', 'outflow', '20m', 'Weir', '', '', '', 'Weir', 'outflow', 'Wetland', '', '', '30m', '', '15m', '0m', '2m', '2m', '15m', 'outflow', '10m', '2m', '2m', '2m', '5m', 'Weir', '20m', '', '8m', '0m', '10m', '', '', '2m', 'wetlands', '', '15m', '', '', '', '', 'Weir', 'outflow', 'mid', 'outflow', 'outflow', 'Weir', '2m', '10m', '2m', '', '8m', '', 'Wetland', '8m', '0m', 'Weir', '2m', '', '15m from Camp Creek Outflow', '', 'outflow', '0m', '3m', '8m', '30m']
['Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Gull River ', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Shoreline', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Dock ', 'Dock ', 'Dock ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Rain Water', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Shoreline', 'Shoreline', 'Shoreline', 'Gull Bay ', 'Gull Bay ', 'Gull River ', 'Camp Creek ', 'Camp Creek ', 'Dock ', 'Shoreline', 'Rackety Creek Outflow ', 'Little Bob Lake', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Rackety Creek Outflow ', 'Rackety Creek Outflow ', 'Gull Bay ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Gull Bay ', 'Gull River ', 'Little Bob Lake ', 'GullBay ', 'Gull Lake Outflow ', 'Gull Bay ', 'Gull Bay ', 'Camp Creek ', 'Camp Creek ', 'Little Bob Lake ', 'Gull Lake Outflow ', 'Gull Bay ', 'Rackety Creek Outflow ', 'Rackety Creek Upstream', 'Rackety Creek Outflow ', 'Rackety Creek Outflow ', 'Rackety Creek ', 'Rackety Creek Upstream', 'Rackety Creek Outflow ', 'Rackety Creek ', 'Rackety Creek  ', 'Rackety Creek Upstream', 'Gull Lake Outflow ', 'Gull Bay ', 'Camp Creek ', 'Rackety Creek Outflow ', 'Gull River ', 'Dock ', 'Camp Creek ', 'Little Bob Lake', 'Camp Creek ', 'Dock ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Dock ', 'Camp Creek ', 'Dock ', 'Shoreline', 'Gull River  ', 'Gull River ', 'Rackety Creek at Weir ', 'Rackety Creek Midstream ', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Gull River ', 'Shoreline', 'Camp Creek ', 'Dock ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Rain   ', 'Rackety Creek Outflow ', 'Rackety Creek Outflow ', 'Camp Creek ', 'Camp creek ', 'rain   ', 'Gull Lake outflow ', 'Gull Lake outflow ', 'Dock ', 'Rackety Creek ', 'Bob Lake', 'Bob Lake', 'Camp Creek ', 'Gull Bay ', 'Camp Creek ', 'Gull Bay ', 'Camp Creek ', 'Gull Bay ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Gull Bay ', 'Gull Bay ', 'Camp Creek ', 'Gull Bay ', 'Gull Bay', 'Gull River ', 'Rain', 'Dock ', 'Gull River Output ', 'Gull River ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Gull Bay ', 'Camp Creek ', 'Dock ', 'Well #1', 'Gull River ', 'Camp Creek ', 'Camp Creek Outflow ', 'Shoreline ', 'Gull River ', 'Camp Creek ', 'Rackety Creek Outflow ', 'Gull Bay ', 'Camp Creek ', 'Well #4', 'Well #2', 'Rackety Creek Outflow ', 'Camp Creek ', 'Rackety Creek Outflow ', 'Camp Creek ', 'Well #3', 'Camp Creek ', 'Dock ', 'Dock ', 'Shoreline ', 'South western point 10 meters southwest of SWP - NaN', 'Shoreline ', 'Gull Lake ', 'Camp creek ', 'Camp Creek ', 'Gull Bay ', 'Rackety Creek Outflow ', 'Gull River ', 'Camp Creek ', 'Gull Bay ', 'Little Bob Lake', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Well #1', 'Camp Creek ', 'Camp Creek ', 'Rackety creek Outflow ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Shoreline ', 'South western point 10 meters southwest of SWP', 'Gull Lake ', 'Dock ', 'Camp Creek ', 'Camp Creek ', 'Well #1', 'Camp Creek ', 'Gull Lake ', 'Gull Lake ', 'Dock ', 'Camp Creek ', 'Gull Lake ', 'Dock ', 'Shoreline ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Well #3', 'Gull Bay ', 'Dock ', 'Shoreline ', 'Shoreline ', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Rackety Creek Outflow ', 'Gull Bay ', 'Gull Bay ', 'Gull Bay ', 'Gull River ', 'Gull River ', 'Shoreline', 'Gull River ', 'Dock ', 'Shoreline ', 'Rackety Creek ', 'Rackety Creek  ', 'Water', 'Camp Creek ', 'Well #1', 'Well #1 ', 'Well #2', 'Well #4 ', 'Well #3', 'Well #3', 'Dock ', 'Camp Creek ', 'Gull Lake ', 'Shoreline', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Rackety Creek Outflow ', 'Well #4', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Dock ', 'Camp Creek ', 'Gull Lake ', 'Well #3', 'Camp Creek ', 'Camp Creek ', 'Camp Creek ', 'Shoreline ', 'Camp Creek ', 'Rackety Creek Outflow ', 'Camp Creek ', 'Shoreline', 'Water', 'well #4', 'Camp Creek ', 'Camp Creek ', 'Dock ', 'Well #1', 'Rackety Creek Outflow ', 'Rackety Creek Outflow ', 'Shoreline ', 'Dock ', 'Well #2', 'Well #4', 'Shoreline', 'Camp Creek ', 'Dock ', 'Dock ', 'Camp Creek ', 'Camp Creek ', 'Dock ', 'Camp Creek ', 'Camp Creek ', 'Well #2', 'Camp Creek ', 'Well #1', 'Rackety Creek Outflow ', 'Rackety Creek Outflow ', 'Gull River ', 'Rackety Creek Outflow ', 'Rackety Creek Outflow ', 'well #2 ', 'well#3', 'Rackety Creek Outflow ', 'Rackety Creek Outflow ', 'Camp Creek ', 'Camp Creek ', 'well #2 ', 'well #3', 'Rackety Creek Outflow ', 'Dock ', 'Camp Creek ', 'Shoreline ', 'Camp Creek ', 'well #2 ', 'Rackety Creek Outflow ', 'Camp Creek ', 'Dock ', 'Dock ', 'Dock ', 'Camp creek ', 'Camp creek ', 'Well #4', 'Rackety Creek Outflow ', 'Camp creek ', 'Well #1', 'well #4', 'Gull Lake ', 'Camp creek ', 'Camp creek ', 'Gull River ', 'Well #4', 'Camp Creek ', 'well #1', 'Camp Creek ', 'Well #4', 'well #2 ', 'Camp Creek ', 'Gull Bay ', 'Gull Bay ', 'Camp creek ', 'Well #4', 'Rackety Creek Outflow ', 'Gull Bay ', 'Camp Creek ', 'Well #3', 'Camp Creek ', 'Gull Bay ', 'Gull Bay ', 'Well #1', 'Rackety Creek Outflow ', 'Camp Creek ', 'Well #2', 'Well #2', 'Well #4', 'Well #3', 'Camp creek ', 'Camp creek ', 'Well #1', 'Camp Creek ', 'Gull Bay ', 'Rackety Creek Outflow ', nan, 'Gull River ', 'Small dock on Gull Lake', 'Rackety Creek Outflow ', 'Gull Bay ', 'Gull River ', 'Camp creek ', 'Well #6', 'Well #3', 'Well #4', 'Camp Creek ', 'Gull Bay ', 'Gull Bay ', 'Well #3', 'Gull Bay ', 'Gull Bay ', 'Well #2', 'Gull Bay ', 'Gull Bay ', 'Camp Creek ', 'Gull River ', 'Camp creek ', 'Gull Bay ', 'Camp Creek ', 'Rain ', 'Well #2', 'Well #3', 'Camp Creek ', 'Camp creek ', 'Camp Creek ', 'Well #1', 'Well #4', 'Gull Bay ', 'Shoreline', 'Gull Bay ', 'Rackety Creek Outflow ', 'Gull River ', 'Rackety Creek Outflow ', 'Gull Bay ', 'Camp creek ', 'Rackety Creek Outflow ', "Miner's Bay ", 'Gull River ', 'Gull Bay ', 'Gull Bay ', 'Camp Creek ', 'Gull Bay ', 'Well #3', 'Gull Bay ', ' Gull Bay ', ' Gull Bay ', 'Well #3', 'Well #3', 'Gull River ', 'camp creek ', 'Well #2', ' Gull Bay ', 'Well #4', 'Rain ', 'Well #1', 'North Pigeon Lake Inlet, surface at creek', 'Camp Creek ', 'Camp creek ', 'Camp creek ', 'Camp creek ', 'Camp creek ', 'Camp Creek ', ' Gull Bay ', ' Gull Bay ', 'Gull River ', 'Well #2', 'Rackety Creek Outflow ', 'Well #4', 'Camp Creek ', ' Gull Bay ', ' Gull Bay ', 'Camp Creek ', 'Rackety Creek Outflow ', 'Well #1', 'Gull Lake ', 'Well #3', 'Camp creek ', 'Gull River ', 'Gull River ', 'Gull River ', 'Gull Bay ']

In [5]:
data['main_location'] = jj
data['description of location'] = kk

data.head()

mom = pd.DataFrame(data['Location'].value_counts())
mom.head(15)

                            Location
Camp Creek (Weir)                 37
Camp Creek (Outflow)              36
Camp Creek (Bridge)               25
Dock (0m)                         21
Camp Creek (Mid)                  15
Camp Creek (Wetlands)             15
Well #3                           14
Camp creek (outflow)              13
Well #1                           12
Well #4                           12
Shoreline                         12
Rackety Creek Outflow (0m)        10
Well #2                           10
Camp Creek (mid)                  10
Gull Bay (15m)                    10

In [6]:
data['main_location'].unique()
data['main_location'] = data['main_location'].apply(lambda x: str(x).lower())
data['main_location'] = data['main_location'].apply(lambda x: x.replace(' ', ''))
data['main_location'] = data['main_location'].apply(lambda x: x.replace('#', ''))
data.head()

,Location,Temperature (C ),pH,Conductivity (uS/cm),DO mg/L,DO %,Average PO,Date,Time,year,PO (ug/L-1),main_location,description of location
0,Gull Bay (6m),18.8,7.26,68.1,7.73,84.1,0.027,05-Aug-19,2:00:00 PM,2019,0.000000,gullbay,6m
1,Gull Bay (12m),9,6.89,55.1,9.29,81.3,0.027,05-Aug-19,2:00:00 PM,2019,26.666667,gullbay,12m
2,Gull Bay (15m),7.8,6.91,54.3,11.56,96.2,0.020,05-Aug-19,2:00:00 PM,2019,20.000000,gullbay,15m
3,Gull River (0m),24.2,7.58,74.4,6.92,87.7,0.020,05-Aug-19,2:00:00 PM,2019,20.000000,gullriver,0m
4,Gull Bay (1m),24.3,7.35,71.5,5.37,64.3,0.033,05-Aug-19,2:00:00 PM,2019,33.333333,gullbay,1m

In [7]:
data.groupby(['main_location']).mean(['Average PO'])

,Average PO,year,PO (ug/L-1)
main_location,,,
boblake,0.034500,2021.000000,34.500000
campcreek,0.150534,2021.404762,145.993778
campcreekoutflow,0.234000,2022.000000,234.000000
dock,0.051069,2021.433333,49.283333
gullbay,0.048186,2021.135135,45.168919
gulllake,0.064889,2022.000000,64.648148
gulllakeoutflow,0.093500,2021.000000,37.333333
gullriver,0.044296,2021.592593,44.266667
gullriveroutput,0.064000,2021.000000,64.000000
littleboblake,0.025500,2021.200000,20.400000
miner'sbay,0.040000,2022.000000,40.000000
nan,0.527000,2022.000000,526.666667
"northpigeonlakeinlet,surfaceatcreek",0.027000,2022.000000,26.666667
racketycreek,0.038833,2021.333333,38.611111
racketycreekatweir,0.020000,2021.000000,20.000000
racketycreekmidstream,0.027000,2021.000000,26.666667
racketycreekoutflow,0.049611,2021.736842,46.934211
racketycreekupstream,0.061333,2021.000000,61.111111
rain,0.126800,2021.400000,126.800000
rainwater,0.063000,2019.000000,63.333333
shoreline,0.048348,2021.347826,48.275362
smalldockongulllake,0.067000,2022.000000,66.666667
southwesternpoint10meterssouthwestofswp,0.024000,2022.000000,24.000000
southwesternpoint10meterssouthwestofswp-nan,0.030000,2022.000000,30.000000
water,0.048000,2022.000000,47.916667
well1,0.627071,2022.000000,627.047619
well2,0.665769,2022.000000,618.142857
well3,0.725143,2022.000000,634.510417
well4,0.293067,2022.000000,293.100000
well6,0.210000,2022.000000,210.000000

In [8]:
mkm = pd.DataFrame(data.groupby(['Location']).mean(['Average PO']))
mkm.head()

                 Average PO    year  PO (ug/L-1)
Location
 Gull Bay (0m)        0.033  2022.0         32.5
 Gull Bay (10m)       0.060  2022.0         60.0
 Gull Bay (15m)       0.070  2022.0         70.0
 Gull Bay (2m)        0.058  2022.0         58.0
 Gull Bay (8m)        0.028  2022.0         27.5

In [9]:
datacount = pd.DataFrame(data['main_location'].value_counts())

In [10]:
datacount.head()

                     main_location
campcreek                      168
gullbay                         74
racketycreekoutflow             38
dock                            30
gullriver                       27

In [11]:
#datacount = datacount['main location'].drop("miner'sbay", inplace = True)
#datacount = datacount.drop('smalldockongulllake', axis = 1, inplace = True)
#datacount = datacount.drop('southwesternpoint10meterssouthwestofswp-nan', inplace = True)
#datacount = datacount.drop('nan', inplace = True)
#datacount = datacount.drop('southwesternpoint10meterssouthwestofswp', inplace = True)
#datacount = datacount.drop('racketycreekupstream', inplace = True)
#datacount = datacount.drop('gulllakeoutflow', inplace = True)
#datacount = datacount.drop('littleboblake', inplace = True)

In [12]:
edited = datacount.head(10)
edited.head()

                     main_location
campcreek                      168
gullbay                         74
racketycreekoutflow             38
dock                            30
gullriver                       27

In [28]:
lon = []
lat = []
amount = []
concentrations = []

ccw = mkm.loc['Camp Creek (Weir)','Average PO']
ccm = mkm.loc['Camp Creek (mid)','Average PO']
ccb = mkm.loc['Camp Creek (bridge)','Average PO']
cco = mkm.loc['Camp Creek (Outflow)','Average PO']
w1 = mkm.loc['Well #1','Average PO']
w2 = mkm.loc['Well #2','Average PO']
w3 = mkm.loc['Well #3','Average PO']
w4 = mkm.loc['Well #4','Average PO']

Site_list = ['campcreekoutflow', 'campcreekmid', 'campcreekbridge', 'campcreekweir', 'well1', 'well2','well3','well4' ]
for i in Site_list:
    if i == 'campcreekoutflow':
        lon.append(-78.7651242)
        lat.append(44.8842031)
        amount.append(36)
        concentrations.append(0.19)
    elif i == 'campcreekbridge':
        lon.append(-78.7650042)
        lat.append(44.8846007)
        amount.append(25)
        concentrations.append(0.17)
    elif i == 'campcreekmid':
        lon.append(-78.7658542)
        lat.append(44.8852007)
        amount.append(15)
        concentrations.append(0.16)
    elif i == 'campcreekweir':
        lon.append(-78.7660542)
        lat.append(44.8859807)
        amount.append(37)
        concentrations.append(0.12)
    elif i == 'well1':
        lon.append(-78.765829)
        lat.append(44.8877186)
        amount.append(12)
        concentrations.append(0.71)
    elif i == 'well2':
        lon.append(-78.7665542)
        lat.append(44.8858807)
        amount.append(10)
        concentrations.append(0.69)
    elif i == 'well3':
        lon.append(-78.7650051)
        lat.append(44.886097)
        amount.append(14)
        concentrations.append(0.71)
    else:
        lon.append(-78.7651051)
        lat.append(44.885797)
        amount.append(12)
        concentrations.append(0.29)


new = pd.DataFrame(Site_list)
new['lat'] = lat
new['lon'] = lon
new['count'] = amount
new['conc'] = concentrations
new['conc2'] = new['conc'].apply(lambda x: x*1000)
#new['lat'] = new['lat'].apply(lambda x: int(x))
#new['lon'] = new['lon'].apply(lambda x: int(x))
#new['count'] = new['count'].apply(lambda x: int(x))

new.head(8)

well.head()

       0        lat        lon  count  conc
4  well1  44.887719 -78.765829     12  0.71
5  well2  44.885881 -78.766554     10  0.69
6  well3  44.886097 -78.765005     14  0.71
7  well4  44.885797 -78.765105     12  0.29

In [14]:

new.head(10)

well= pd.DataFrame(new.tail(4))
water = pd.DataFrame(new.head(4))

In [27]:
import gmaps
import os
from IPython.display import display
gmaps.configure(api_key='AIzaSyAo3MOw2NTiRZ3phDO9z3TEeyLH9HluaGc')
gull_lake = (44.8851807,-78.7650542)
fig = gmaps.figure(center=gull_lake, zoom_level=15, map_type='SATELLITE')

marker_locations = [(44.8851807,-78.7650542)]

locations = new[['lat','lon']]
weights = new['count']

#markers = gmaps.marker_layer(marker_locations)

heatmap_layer = gmaps.heatmap_layer(well[['lat', 'lon']], weights=well['count'].apply(lambda x: x^5), point_radius = 17)
heatmap_layer1 = gmaps.heatmap_layer(water[['lat', 'lon']], weights=water['count'].apply(lambda x: x^5), point_radius = 17)
fig.add_layer(heatmap_layer)
fig.add_layer(heatmap_layer1)

#fig.add_layer(markers)
fig
display(fig)

Figure(layout=FigureLayout(height='420px'))

In [45]:
fig1 = gmaps.figure(center=gull_lake, zoom_level=15, map_type='TERRAIN', display_toolbar=True)

marker_locations = [(44.8851807,-78.7650542)]

locations1 = well[['lat','lon']]
weights1 = well['count']
locations2 = water[['lat','lon']]
weights2 = water['count']
wells = ['Well #1', 'Well #2', 'Well #3', 'Well #4']
campcreek = ['CC Outflow', 'CC Mid', 'CC Bridge', 'CC Weir']

markerswells = gmaps.marker_layer(locations1, label = wells)
#starbucks_layer = gmaps.symbol_layer(
    #locations1, fill_color='green', stroke_color='blue', scale=4)
#starbucks_layer1 = gmaps.symbol_layer(
   # locations2, fill_color='green', stroke_color='red', scale=4)
markerwater = gmaps.marker_layer(locations2, label = campcreek)
#gg =  gmaps.symbol_layer(locations1, hover_text = wells)
#fig1.add_layer(starbucks_layer)
#fig1.add_layer(starbucks_layer1)
symbols = gmaps.symbol_layer(
        locations1, fill_color='red', stroke_color='red')
fig1.add_layer(symbols)
symbols2 = gmaps.symbol_layer(
        locations2, fill_color='blue', stroke_color='blue')
fig1.add_layer(symbols2)

fig1.add_layer(markerswells)
fig1.add_layer(markerwater)

fig1


#fig.add_layer(markers)

Figure(layout=FigureLayout(height='420px'))

In [25]:
fig3 = gmaps.figure(center=gull_lake, zoom_level=15, map_type='SATELLITE')

marker_locations = [(44.8851807,-78.7650542)]


heatmap_layer11 = gmaps.heatmap_layer(new[['lat', 'lon']], weights=new['conc2'], point_radius = 17)
heatmap_layer12 = gmaps.heatmap_layer(new[['lat', 'lon']], weights=new['conc2'], point_radius = 17)

fig3.add_layer(heatmap_layer11)
fig3.add_layer(heatmap_layer12)

fig3
#markers = gmaps.marker_layer(marker_locations)

#fig.add_layer(markers)

Figure(layout=FigureLayout(height='420px'))

In [ ]:
new_york_coordinates = (40.75, -74.00)
fig = gmaps.figure(center=new_york_coordinates, zoom_level=12)
fig

In [ ]:
pip install gmplot

In [ ]:
import gmplot

In [ ]:
gmap3 = gmplot.GoogleMapPlotter(44.863,  -78.77667, 13)
display(gmap3)